// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdM5Yt-c6-77iIJELjewUSxU7JznjImLs',
    appId: '1:634458892983:web:87933d7fdd9d950b55fb32',
    messagingSenderId: '634458892983',
    projectId: 'scaler-50378',
    authDomain: 'scaler-50378.firebaseapp.com',
    storageBucket: 'scaler-50378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDELMZGBg_sSDXSg_jzN9Azas1sSQbtcH0',
    appId: '1:634458892983:android:004586072a9dda0055fb32',
    messagingSenderId: '634458892983',
    projectId: 'scaler-50378',
    storageBucket: 'scaler-50378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAftLfZDdbNPPZkdaDHXoo_F5EViTSAlkM',
    appId: '1:634458892983:ios:ea450536f953f62555fb32',
    messagingSenderId: '634458892983',
    projectId: 'scaler-50378',
    storageBucket: 'scaler-50378.appspot.com',
    iosBundleId: 'com.example.scalerCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAftLfZDdbNPPZkdaDHXoo_F5EViTSAlkM',
    appId: '1:634458892983:ios:e8c805ea5d995a8555fb32',
    messagingSenderId: '634458892983',
    projectId: 'scaler-50378',
    storageBucket: 'scaler-50378.appspot.com',
    iosBundleId: 'com.example.scalerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdM5Yt-c6-77iIJELjewUSxU7JznjImLs',
    appId: '1:634458892983:web:cda128fd60f37d8155fb32',
    messagingSenderId: '634458892983',
    projectId: 'scaler-50378',
    authDomain: 'scaler-50378.firebaseapp.com',
    storageBucket: 'scaler-50378.appspot.com',
  );
}
